### ISSUE TITLE
Default Argument in example video precedes required argument, but lesson says doing so is confusing

### ISSUE THREAD

**Issue by rkerian** [learn-co-curriculum/methods-default-arguments#12]
The lesson states "defining the default argument first is confusing... it is conventional to place any default arguments at the end of an argument list when defining a method that takes in both required and default arguments."

Yet the video example, which is our first time seeing a default argument in action, uses the default argument (phrase = "Hello") before the required argument (x) in the example method. This is confusing.

![image](https://cloud.githubusercontent.com/assets/17804780/13731589/1df8ca06-e92a-11e5-84da-14c84f8a7e65.png)

**Comment by PeterBell** [comment]
Hi @rkerian thanks so much for the input! I agree. Having an example of the method where the first argument (phrase) gets the default value does seem inconsistent with the suggestion that arguments with defaults should be the last ones. Going to make a note to get this re-recorded at some point in time.

**Comment by AnnJohn** [comment]
@mendelB - easiest solution for this is probably to remove the video for the repurposed track

**Comment by trekkin** [comment]
I also found this confusing and was going to submit this as an issue until I saw one already existed.  If there isn't an updated video yet, perhaps it could be called out in the text?

**Comment by sgharms** [comment]
Thanks for reporting this issue. We're aware of it and are tracking it in https://github.com/learn-co-curriculum/methods-default-arguments/issues/19

We're closing this issue but invite you to follow https://github.com/learn-co-curriculum/methods-default-arguments/issues/19.
