### ISSUE TITLE
Video techniques differ from those advised

### ISSUE THREAD

**Issue by emilycroft** [learn-co-curriculum/methods-default-arguments#18]
In the video for this lesson, the default argument is positioned in the first argument location. The lesson goes on to describe that typical ruby convention would always want to place a lone default argument as the end of an arguments list and not at the beginning. This discrepancy is a bit counterintuitive and confusing as someone first learning about this concept.

**Comment by cjbrock** [comment]
@emilycroft Thank you for this note! We actually have an outstanding issue for this already open, #12. If you'd like to be updated when we fix the issue, please follow that issue.
--Corinna
