### ISSUE TITLE
Code isn't running 

### ISSUE THREAD

**Issue by klpapke215** [learn-co-curriculum/methods-default-arguments#20]
Hello,
I've had my code reviewed by a tech coach, who said that it is exactly what the solution has, but when I run learn test it comes up with an error. 
![screen shot 2018-05-01 at 10 37 26 am](https://user-images.githubusercontent.com/38473506/39477061-1623b08a-4d2c-11e8-994e-7214d999c315.png)

**Comment by drakeltheryuujin** [comment]
Hi @klpapke215,

Does this issue pertain to [this lab](https://github.com/learn-co-curriculum/say-hello-ruby)? If so, your solution is correct, and the tests run with that solution.

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not bugs with the Learn platform (such as [lights not turning green](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

Check the [Learn Help Center](http://help.learn.co/) to see if there is an answer to your problem there.

If you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
